<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="NouvelleBonDistribution.aspx.cs" Inherits="ProjetSynthese_1._0.NouvelleBonDistribution" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <br/><br/>
    <asp:Label ID="lblNum" runat="server" Text="Numero Bon distribution "></asp:Label>
    <asp:TextBox ID="txtNumBonDistribution" runat="server" Enabled="false"></asp:TextBox><br/>

    <asp:Label ID="lblFiliale" runat="server" Text="Filiale "></asp:Label>
    <asp:DropDownList ID="cmbFiliale" runat="server" OnSelectedIndexChanged="cmbFournisseur_SelectedIndexChanged" AutoPostBack="true"></asp:DropDownList><br/>
    
    <asp:TextBox ID="txtInfoFiliale" runat="server" Height="41px" Width="247px" Enabled="False"></asp:TextBox><br/>

    <asp:Label ID="lblDateBonDistribution" runat="server" Text="Date Bon distribution "></asp:Label>
    <asp:Calendar ID="calDateBonDistribution" runat="server" Height="16px" Width="127px"></asp:Calendar><br/>

    <hr/>

    <asp:Label ID="lblArticle" runat="server" Text="Article "></asp:Label>
    <asp:TextBox ID="txtArticle" runat="server"></asp:TextBox>
    <asp:Button ID="btnRechercher" runat="server" Text="Rechercher" OnClick="btnRechercher_Click"/>
    <br/>

    <asp:GridView ID="gridArticles" runat="server" Height="50px" Width="125px" OnSelectedIndexChanged="gridArticles_SelectedIndexChanged" AutoGenerateSelectButton="True">
    </asp:GridView><br/>

     <asp:Label ID="lblNumArticle" runat="server" Text="Numero "></asp:Label>
    <asp:TextBox ID="txtNum" runat="server" Enabled="false"></asp:TextBox><br/>

    <asp:Label ID="lblNomArticle" runat="server" Text="Nom "></asp:Label>
    <asp:TextBox ID="txtNom" runat="server" Enabled="false"></asp:TextBox><br/>

    <asp:Label ID="lblQuantite" runat="server" Text="Quantite "></asp:Label>
    <asp:TextBox ID="txtQuantite" runat="server"></asp:TextBox><br/>

    <asp:Button ID="btnAjouter" runat="server" Text="Ajouter" OnClick="btnAjouter_Click" Enabled="false"/>

    <hr/>

    <asp:GridView ID="gridViewDistribution" runat="server" Height="50px" Width="125px" AutoGenerateDeleteButton="True" OnRowDeleting="gridViewCommande_RowDeleting">
    </asp:GridView><br/>

    <hr/>
    <asp:Button ID="btnEnregistrer" runat="server" Text="Enregistrer" Enabled="false" OnClick="btnEnregistrer_Click"/>



</asp:Content>
