<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="NouvelleCommande.aspx.cs" Inherits="ProjetSynthese_1._0.NouvelleCommande" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <link href="Content/Grid.css" rel="stylesheet" />

    <br />
    <div class="h2 text-primary">Placer commande</div>

    <table class="table table-responsive">
        <tr>
            <td>
                <asp:Label ID="lblNum" runat="server" Text="Numero Commande "></asp:Label>
            </td>
            <td>
                <asp:TextBox ID="txtNumCommande" runat="server" Enabled="false" CssClass="form-control"></asp:TextBox>
            </td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>
                <asp:Label ID="lblFournisseur" runat="server" Text="Fournisseur "></asp:Label>
            </td>
            <td>
                <div class="form-group">
                    <asp:DropDownList ID="cmbFournisseur" runat="server"
                        OnSelectedIndexChanged="cmbFournisseur_SelectedIndexChanged"
                        AutoPostBack="true" CssClass="form-control">
                    </asp:DropDownList>
                </div>
            </td>
            <td>
                <asp:TextBox ID="txtInfoFpurnisseur" runat="server" Height="100px" TextMode="MultiLine" Enabled="False" CssClass="form-control"></asp:TextBox>
            </td>
            <td></td>
        </tr>
        <tr>
            <td>
                <asp:Label ID="lblDateCommande" runat="server" Text="Date commande "></asp:Label>
            </td>
            <td>
                <input id="Text1" type="text" value="<%= DateTime.Now.ToShortDateString() %>" class="form-control" readonly/>
            </td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>
                <asp:Label ID="lblArticle" runat="server" Text="Article "></asp:Label>
            </td>
            <td>
                <asp:TextBox ID="txtArticle" runat="server" CssClass="form-control"></asp:TextBox>
            </td>
            <td>
                <asp:Button ID="btnRechercher" runat="server" Text="Rechercher"
                    OnClick="btnRechercher_Click" CssClass="btn btn-primary btn-block" />
            </td>
            <td></td>
        </tr>
        <tr>
            <td colspan="4">
                <asp:GridView ID="gridArticles" runat="server" OnSelectedIndexChanged="gridArticles_SelectedIndexChanged"
                    AutoGenerateDeleteButton="False" AutoGenerateSelectButton="True" CssClass="table Grid">
                </asp:GridView>
            </td>
        </tr>

        <tr>
            <td>
                <asp:Label ID="lblNumArticle" runat="server" Text="Numero "></asp:Label>
            </td>
            <td>
                <asp:TextBox ID="txtNum" runat="server" Enabled="false" CssClass="form-control"></asp:TextBox>
            </td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>
                <asp:Label ID="lblNomArticle" runat="server" Text="Nom "></asp:Label>
            </td>
            <td>
                <asp:TextBox ID="txtNom" runat="server" Enabled="false" CssClass="form-control"></asp:TextBox>
            </td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>
                <asp:Label ID="lblPrix" runat="server" Text="Prix "></asp:Label>
            </td>
            <td>
                <asp:TextBox ID="txtPrix" runat="server" Enabled="false" CssClass="form-control"></asp:TextBox>
            </td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>
                <asp:Label ID="lblQuantite" runat="server" Text="Quantite"></asp:Label>
            </td>
            <td>
                <asp:TextBox ID="txtQuantite" runat="server" Text="0" CssClass="form-control"></asp:TextBox>

                <asp:RequiredFieldValidator ID="RequiredFieldValidatorTxtQuantite" runat="server" 
                    ErrorMessage="Champ obligatoire" ForeColor="Red" ControlToValidate="txtQuantite" Enabled="false">
                </asp:RequiredFieldValidator>
                <asp:Label ID="lblResultatTxtQuantite" runat="server" Text="" ForeColor="Red"></asp:Label>

            </td>
            <td>
                <asp:Button ID="btnAjouter" runat="server" Text="Ajouter" OnClick="btnAjouter_Click"
                    Enabled="false" CssClass="btn btn-primary btn-block" />
            </td>
            <td></td>
        </tr>
        <tr>
            <td colspan="4">
                <div class="h2 text-primary">Ligne commande</div>
            </td>
        </tr>
        <tr>
            <td colspan="4">
                <asp:GridView ID="gridViewCommande" runat="server" AutoGenerateDeleteButton="True" OnRowDeleting="gridViewCommande_RowDeleting" CssClass="table table-responsive Grid">
                </asp:GridView>
            </td>
        </tr>
        <tr>
            <td>
                <div class="h2 text-primary">Montant total</div>
            </td>

            <td>

                <asp:TextBox ID="txtMontant" runat="server" Enabled="False"
                    CssClass="form-control"></asp:TextBox>
            </td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <asp:Button ID="btnEnregistrer" runat="server" Text="Enregistrer" Enabled="false" OnClick="btnEnregistrer_Click" CssClass="btn btn-primary btn-block" />

            </td>

        </tr>
    </table>

</asp:Content>
